#!/bin/tcsh -f
# Scriptname: filecheck
# Usage: filecheck filename
alias Usage 'echo "    Usage: $0 filename\!*" ; exit 1'
alias Error 'echo "    Error: \!* "; exit 2'
set file=$1
if ( $#argv == 0 ) then
   Usage
endif
if ( ! -e $file ) then
	Error "$file does not exist"
endif
