#!/bin/csh -f
# This script is called grade
echo -n "What was your grade? "
set grade = $<
if ( $grade >= 90 && $grade <= 100 ) then
	echo "You got an A\!"
else if ( $grade > 79 ) then
	echo "You got a B"
else if ( $grade > 69 ) then
	echo "You're average"
else
	echo "Better study"
endif
