#!/bin/ksh
# Program name: ttype
# Purpose: set the terminal type
# Author: Andy Admin
COLUMNS=60
LINES=1
PS3="Please enter the terminal type: "
select choice in wyse50 vt200 vt100 sun
do 
	case $REPLY in
	1)
		export TERM=$choice
		print "TERM=$choice"
		break;;		               # break out of the select loop
	2 | 3 )
		export TERM=$choice	
		print "TERM=$choice"
		break;;
	4)
		export TERM=$choice	
		print "TERM=$choice"
		break;;
	*) 
		print "$REPLY is not a valid choice. Try again" 1>&2
		 	;;
	esac
done
