######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 13 14:03:01 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myWidget.h
SOURCES += main.cpp
