######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 13 13:41:56 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += click.cpp
