######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 13 17:37:17 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myWidget.h
FORMS += form.ui
SOURCES += main.cpp
